### PR TITLE
Java CI : fix project key

### PR DESCRIPTION
**Pull request by HugoKulesza**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Bug fix :  the java CI project key was wrong for the full CI, not allowing comparison between main and branches

### CODE REVIEW

**Comment by jeandemanged** [comment]
@HugoKulesza maybe also fix existing badges links and add additional badges in the README.md ?

**Comment by HugoKulesza** [comment]
> @HugoKulesza maybe also fix existing badges links and add additional badges in the README.md ?

I think that an additional badge was already added but was not filled since the full-ci java sonar analysis was not using the right project id, we now have two sonar analyses

**Comment by HugoKulesza** [comment]
image
It's the badge under the text @jeandemanged

**Comment by jeandemanged** [comment]
> image It's the badge under the text @jeandemanged

sorry, was not precise enough, it would be nice to:
- fix the broken first badge CI "no status" as can be seen on your picture
- have all badges together, not most badges above text and another one alone below text
- sonar:
  - make it clear what is java and what is python
  - we should have both quality and coverage for both java and python

**Comment by HugoKulesza** [comment]
> > image It's the badge under the text @jeandemanged
> 
> sorry, was not precise enough, it would be nice to:
> 
>     * fix the broken first badge CI "no status" as can be seen on your picture
> 
>     * have all badges together, not most badges above text and another one alone below text
> 
>     * sonar:
>       
>       * make it clear what is java and what is python
>       * we should have both quality and coverage for both java and python

- I'll look to fix that
- You are right I will move them
- I can precise java and python, we do not check for java side coverage (it was a conscious choice we made with @geofjamg and not a mistake)

**Comment by HugoKulesza** [comment]
@jeandemanged I made some changes, is it better ?
I just precised a graalvm version in full-ci that i forgot in #866 to fix the general CI

**Pull request merged**
