### PR TITLE
Add new nad parameters

### PR DESCRIPTION
**Pull request by EtienneLt**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Feature

**What is the new behavior (if this is a feature change)?**
We expose to python API some new NAD parameters 

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Review by flo-dup — COMMENTED** [review]
Could you also add substationDescriptionDisplayed?

**Comment by EtienneLt** [comment]
> Could you also add substationDescriptionDisplayed?

I add it to the list

**Comment by EtienneLt** [comment]
done

**Review by geofjamg — CHANGES_REQUESTED** [review]
A little bit of documentation would be welcomed. A table in the NAD section with all possible parameters and un short description would be perfect.

**Review by So-Fras — APPROVED** [review]

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
