### PR TITLE
add ampl export

### PR DESCRIPTION
**Pull request by EtienneLt**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
feature

**What is the new behavior (if this is a feature change)?**
add the network AMPL export

### CODE REVIEW

**Comment by geofjamg** [comment]
We should add a TU to ensure we are not missing GraalVM meta data

**Comment by EtienneLt** [comment]
> We should add a TU to ensure we are not missing GraalVM meta data

in java or in python ?

**Comment by geofjamg** [comment]
> > We should add a TU to ensure we are not missing GraalVM meta data
> 
> in java or in python ?

In python

**Comment by EtienneLt** [comment]
> > > We should add a TU to ensure we are not missing GraalVM meta data
> > 
> > 
> > in java or in python ?
> 
> In python

done

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
