### PR TITLE
Windows CI fixed and add basic import test step in CI

### PR DESCRIPTION
**Pull request by EtienneLt**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Comment by obrix** [comment]
Maybe linked to the following issue : https://github.com/actions/runner-images/issues/10020

**Comment by EtienneLt** [comment]
it seems to work

**Comment by obrix** [comment]
Yes, I think we will be able to remove the workaround once they fix their runner image. 
Also I added a simple standalone_test.py that only import powsybl and print version to run before the full tests. That was just to debug at first but I am wondering if it could be a good idea to let it in place to be able to quickly see if an issue is related to the whole import and init of pypowsybl or a to a specific test. 
Any opinion @EtienneLt @geofjamg ?

**Comment by obrix** [comment]
It looks like the windows image has been fixed.

**Review by obrix — APPROVED** [review]

**Pull request merged**
