### PR TITLE
Modify powsybl-diagram apis

### PR DESCRIPTION
**Pull request by So-Fras**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Comment by geofjamg** [comment]
@So-Fras could you please update this PR ?

**Comment by geofjamg** [comment]
We usually used not to break python code compatibility, we should probably think about adding deprecated backward old API (the LayoutParameters) ?

**Comment by So-Fras** [comment]
I understand. But I think it would be confusing to keep both, especially since the old LayoutParameters contained everything but layout parameters!

**Comment by So-Fras** [comment]
In the end, we have not broken compatibility with previous versions. If users use the old LayoutParameters class, a warning is issued to encourage them to switch to the new SldParameters class.

**Review by geofjamg — APPROVED** [review]
@So-Fras it could be done in another PR but we should also improve the user guide by describing better SLD write parameters

**Comment by So-Fras** [comment]
Agreed. I was also thinking of offering full customization possibilities for Python users and fully document parameters.

**Comment by EtienneLt** [comment]
Are we okay ? Do I merge ?

**Comment by geofjamg** [comment]
> Are we okay ? Do I merge ?

yes

**Pull request merged**
