### PR TITLE
Read/write for tap changers

### PR DESCRIPTION
**Pull request by sylvlecl**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Feature

**What is the new behavior (if this is a feature change)?**

We can list and update ratio tap changers, as well as phase tap changers.

### CODE REVIEW

**Comment by sylvlecl** [comment]
@geofjamg I removed the redundant "tap_position" attributes from TWT table

**Review by geofjamg — COMMENTED** [review]
Maybe we should do it also for 3 windings transformers?

**Comment by sylvlecl** [comment]
> Maybe we should do it also for 3 windings transformers?

Indeed, I was wondering if we should do it in the same tables or not. I think we will not be able to, because for the 3 windings we will need a mixed index.

**Comment by geofjamg** [comment]
> mixed

I would got for same table but the second index (with value 1?) won't be used when querying for a 2 windings transformer.

**Comment by sylvlecl** [comment]
Closing since the 2 windings transformers change has been included in #126 .
Work on 3 windings transformers remains in the todo list though.

**Pull request closed without merging**
