### PR TITLE
add fictitious attribute

### PR DESCRIPTION
**Pull request by EtienneLt**
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#465

### CODE REVIEW

**Comment by AnkurArohi** [comment]
@EtienneLt 
Is this done and implemented?

**Comment by EtienneLt** [comment]
> @EtienneLt Is this done and implemented?

no it was not finished. But I did not know if you are doing it ?

**Comment by AnkurArohi** [comment]
@EtienneLt 

I understand, that was my plan, but i haven't started with it yet. what was the reason that you had to close this MR?

**Comment by EtienneLt** [comment]
> @EtienneLt
> 
> I understand, that was my plan, but i haven't started with it yet. what was the that you had to close this MR?

well it is in your mr then these one is not needed

**Comment by AnkurArohi** [comment]
@EtienneLt 

I haven't created any MR for this feature, it was rather for https://github.com/powsybl/pypowsybl/pull/464
you can continue with your MR, I would anyways need more time for the MR correction based on the comments of Sylvian

**Pull request closed without merging**
