### PR TITLE
[WIP] Simplify build using skbuild + move C extension to pypowsybl package

### PR DESCRIPTION
**Pull request by sylvlecl**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Build refactoring

**What is the current behavior?** *(You can also link to an open issue here)*

- C extension is built using in-house distutils overrides (for Extension and build_ext commands)
- C extension libraries are installed to root package, which is not best practice

**What is the new behavior (if this is a feature change)?**

Libraries are installed in pypowsybl package.
We use [scikit-build](https://scikit-build.readthedocs.io/en/latest/usage.html) for the build.

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

`_pypowsybl` is moved to `powsybl._pypowsybl`. However, it is not supposed to be used by the user.

### CODE REVIEW

**Comment by geofjamg** [comment]
@sylvlecl it seems that the windows build issue is because with scikit build, ninja cmake generator is used and by default ninja build is parallelized which cause memory issue on github action worker during native image build. In main branch code, this is VS generator which is selected explicitely and according to the doc, the build is not parallelized by default.
So I can see 2 solutions:
  - force generator to be VS on Windows
  - or force ninja to not parallelize build
https://scikit-build.readthedocs.io/en/latest/generators.html#build-system-generator

**Comment by sylvlecl** [comment]
>     * force generator to be VS on Windows
> 
>     * or force ninja to not parallelize build
>       https://scikit-build.readthedocs.io/en/latest/generators.html#build-system-generator

@geofjamg I gave a try to both suggestions. Not parallelizing seems to not change anything, forcing MSVC makes graalvm build succeed, but another error is encountered down the road (looks like a path parsing issue ...):
```
ModuleNotFoundError: No module named '_skbuild\\win-amd64-3'
```

I am gonna give up on skbuild which does not seem to help a lot.
However I'll move libraries to `pytpowsybl` package in another PR.

**Comment by geofjamg** [comment]
> > ```
> > * force generator to be VS on Windows
> > 
> > * or force ninja to not parallelize build
> >   https://scikit-build.readthedocs.io/en/latest/generators.html#build-system-generator
> > ```
> 
> 
> @geofjamg I gave a try to both suggestions. Not parallelizing seems to not change anything, forcing MSVC makes graalvm build succeed, but another error is encountered down the road (looks like a path parsing issue ...):
> 
> 
> ```
> ModuleNotFoundError: No module named '_skbuild\\win-amd64-3'
> ```
> 
> 
>      
>   
> 
> I am gonna give up on skbuild which does not seem to help a lot.
> However I'll move libraries to `pytpowsybl` package in another PR.

Yes, this is the most interesting part of this PR. Having all our libs and files stored at the root of python package folder is really dirty and we should fix it as soon as possible.

**Comment by sylvlecl** [comment]
Closed in favor of #291

**Pull request closed without merging**
